baseURL: https://www.dekeukenvandael.nl
languageCode: nl-nl
title: De Keuken van Dael
theme: "PaperModX"

outputs:
  home:
    - HTML
    - RSS
    - JSON # Required for search

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /recipes/:filename/

pluralizelisttitles: "false"


params:
  title: Keuken van Dael
  description: "Een kijkje in de keuken van Dael"
  author: "Daan Geijs"
  DateFormat: " 2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  hideFooter: true
  ShowReadingTime: true
  ShowShareButtons: true
  EnableImageZoom: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowAuthor: true
  ShowCommentNumber: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  TocSide: 'left'
  tocopen: true
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "favicon.ico"
    appleTouchIcon: "favicon-152.png"

paginate: 10
menu:
  main:
  - name: Recepten
    url: /recipes/
    weight: -120
  - name: Zoeken
    url: /search/
    weight: -115
  - name: Archief
    url: /archives/
    weight: -110