baseURL: https://www.dekeukenvandael.nl
languageCode: nl-nl
title: 'De Keuken van Dael'
theme: "PaperModX"

outputs:
  home:
    - HTML
    - RSS
    - JSON # Required for search

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /recipes/:filename/

pluralizelisttitles: "false"

sitemap:
  changeFreq: "yearly"
  filename: sitemap.xml
  priority: -1

params:
  title: Keuken van Dael
  description: "Een kijkje in de keuken van Daan en Elleke"
  author: "Daan Geijs"
  DateFormat: " 2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  hideFooter: false
  ShowReadingTime: true
  ShowShareButtons: true
  EnableImageZoom: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowAuthor: true
  ShowCommentNumber: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  TocSide: 'left'
  tocopen: true
  cover:
    responsiveImages: true
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.3
      minMatchCharLength: 2
  editPost:
    URL: "https://github.com/daangeijs/dekeukenvandael.nl/content"
    Text: "Stel een wijziging voor" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "favicon.ico"
    appleTouchIcon: "favicon-114.png"

  logo:
    icon: "images/static/logo.svg"
    iconHeight: 150px
    iconWidth: 400px

paginate: 16

menu:
  main:
  - name: Recepten
    url: /recipes/
    weight: 1
  - name: Zoeken
    url: /search/
    weight: 2
  - name: Archief
    url: /archives/
    weight: 3